version = 0.1

[default.deploy.parameters]
stack_name = "broadcast-message"
resolve_s3 = true
s3_prefix = "broadcast-message"
region = "ap-southeast-1"
profile = "sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[dev.deploy.parameters]
stack_name = "broadcast-message"
resolve_s3 = true
s3_prefix = "broadcast-message"
region = "ap-southeast-1"
profile = "sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
